### PR TITLE
Added new icons

### PR DESCRIPTION
**Pull request by visualapps**
Screen Shot 2019-10-10 at 3 02 44 PM

Added
1 -clock
2- stop
3- add
4-loader
5-hamburger
6-user
7-container
8-add user
9-star
10-share
11-sort
12-filter
13-table
14-view
15-disable
16-link
17-wave

### CODE REVIEW

**Comment by IsAmrish** [comment]
@visualapps  -- here are my updates

- table icon looks like a sort of chart type icon. 
- wave icon can look better if it would be a smooth sine wave

- loader, is it gif type icon? (with loading motions)

**Comment by visualapps** [comment]
> @visualapps -- here are my updates
> 
> * table icon looks like a sort of chart type icon.
> * wave icon can look better if it would be a smooth sine wave
> * loader, is it gif type icon? (with loading motions)

@IsAmrish 
Can you give us some examples of table and wave icon?
This are just static fonts not motions.

**Comment by kalyantt** [comment]
LGTM

**Comment by kalyantt** [comment]
Not taking these changes now, will try later, but you might have to check the spelling of STAR it is START with an extra "T"

**Comment by IsAmrish** [comment]
I am merging it now, we can create issue if something is not satisfactory in icons and so...

**Pull request merged**
