### PR TITLE
Pagination background color with kubera background.

### PR DESCRIPTION
**Pull request by is-ashish**
Pagination background color with kubera background.

Issue- 
Screenshot from 2020-10-30 14-33-30

Application dashboard:- change vertical color.

Screenshot from 2020-10-30 18-56-18

Signed-off-by: ashishjain <ashish.jain@mayadata.io>

### CODE REVIEW

**Review by avishnu — APPROVED** [review]
lgtm

**Comment by Pallavi-PH** [comment]
@is-ashish the inactive paginations do not have any background according to new design

**Comment by is-ashish** [comment]
Yes, Inactive pagination numbers will not be any background color. 
De-code background-color have white color but kubera have $sky-blue so getting difference there. @Pallavi-PH

**Comment by is-ashish** [comment]
@Pallavi-PH Addressed changes, PTAL

**Comment by is-ashish** [comment]
@Pallavi-PH In same PR have made vertical line color fix also. PTAL.

**Review by Pallavi-PH — APPROVED** [review]

**Pull request merged**
