### PR TITLE
Updating de-code

### PR DESCRIPTION
**Pull request by Pallavi-PH**
- Replaced product with components and updated alert & tables CSS
- Added code block for `circle badge` sizes
- Added missing button variations

### CODE REVIEW

**Comment by Pallavi-PH** [comment]
**Button variants:**

Screenshot from 2020-02-28 11-17-04
Screenshot from 2020-02-28 11-17-34
Screenshot from 2020-02-28 11-20-17
Screenshot from 2020-02-28 11-20-42
Screenshot from 2020-02-28 11-23-47

**Comment by Pallavi-PH** [comment]
**Alerts:**

Screenshot from 2020-02-28 11-16-37

**Comment by visualapps** [comment]
@avishnu can see the Netlify build script is current or not, Build are failing.

**Comment by Pallavi-PH** [comment]
Screenshot from 2020-03-03 12-23-21

**Comment by visualapps** [comment]
Should we break this PR in three, by component wise?

1. Added new buttons variations (Attach the figma design link) 
2. Modified alerts with latest design (Attach the design if possible)
3. Re-organize the sidebar items (Mention the new hierarchy)
4. Circle badge code block

**Pull request closed without merging**
