### PR TITLE
Updating icons files with v.1.0.2

### PR DESCRIPTION
**Pull request by Pallavi-PH**

### CODE REVIEW

**Review by IsAmrish — COMMENTED** [review]
It looks like - `overview` don't have any icon in front of it. If we have removed `overview`  icon from our icon list, please remove the `overview text` as well
de-code-feedback


One icon name is `loader1`, is it correct? please check this one also!!

**Review by IsAmrish — APPROVED** [review]
LGTM

**Review by IsAmrish — APPROVED** [review]
LGTM

**Review by avishnu — APPROVED** [review]
lgtm

**Pull request merged**
