### PR TITLE
updated dependencies and remove de-code-marketing

### PR DESCRIPTION
**Pull request by Pallavi-PH**
This PR updates the following:

1. Updates all dependencies
2. Removes de-code-marketing
3. Supports upto node version 8
4. Updates HTML DOM elements to supported variation

### CODE REVIEW

**Review by avishnu — APPROVED** [review]
LGTM

**Review by IsAmrish — APPROVED** [review]
LGTM

**Review by is-ashish — APPROVED** [review]
Tested In local setup.All changes are there @Pallavi-PH  
/ LGTM

**Comment by Pallavi-PH** [comment]
> Tested In local setup.All changes are there @Pallavi-PH  
> / LGTM 

Thank you..

**Pull request merged**
